### ISSUE TITLE
v3.2.0 doesn't work properly in my project, but v.3.1.1 did

### ISSUE THREAD

**Issue by RobinMeneust** [cds-astro/aladin-lite#114] opened 2023-08-14 16:56 UTC
### Context

I use Quasar (a framework based on Vue.JS).
The main page of my project has Aladin Lite embedded in it, I load surveys from a URL and I use Aladin Lite events to draw MOCs on it.

### Issues
When Aladin Lite loads (with the following line), I get an error in the console, that I did not get in the previous version:
```JS
A.aladin('#aladin-lite-div', {cooFrame:"ICRSd", survey:'https://alasky.cds.unistra.fr/DSS/DSSColor/',fov:180});
```

![image](https://github.com/cds-astro/aladin-lite/assets/85349121/1e48c65f-68fb-4bc8-9d8e-206cf323eefd)
![image](https://github.com/cds-astro/aladin-lite/assets/85349121/3118adee-50af-478a-a247-62efc4c78dcf)

I also get it in one of your example (without changing anything): 
![image](https://github.com/cds-astro/aladin-lite/assets/85349121/94d55acf-3f49-4532-9a1d-84147e439968)

In my project I also use tabs to switch between "pages", and when I am on the page with Aladin Lite and I go to another one, I get the following error, which I didn't get in v.3.1.1.
![image](https://github.com/cds-astro/aladin-lite/assets/85349121/4f6e59fa-a676-489c-947e-812dd408f8d8)

Even though it won't help you to understand why there are those errors, you can view it at: http://voparis-explore.obspm.fr/browse/Mars, when you load the page or when you click on another tab ('results' for instance).

Is there a way to use the previous version of Aladin Lite without having to host it myself ?

I can provide more code or give more details if needed.

**Comment by bmatthieu3** [comment] 2023-08-15 16:37
I cannot reproduce the E[0] thing error on my side. What is your browser and its version ?
For the changing tab problem, it should work now. I pushed a fix for that

**Comment by RobinMeneust** [comment] 2023-08-15 17:41
I get this error sometimes after refreshing the page at: https://aladin.cds.unistra.fr/AladinLite/doc/API/examples/MOC/ (and I always get it in my project).
This only happens on Firefox, I don't get any error on Chrome.

I am on Windows 10 and I use Firefox 116.0.2 (64-bit).

It looks like that this error doesn't cause any issue in my website. Everything seems to work properly again.
So my main issue was solved, thank you very much!

**Comment by bmatthieu3** [comment] 2023-09-29 12:22
It is possible that the switch from webpack to vite made the bundling less compatible with old browsers. In that recent commit 09d35f591838abecb293b98d5a77047f10d8dcb5 I changed the bundling parameters to make the bundle compatible with older browsers.

**Comment by onekiloparsec** [comment] 2024-02-15 21:48
@RobinMeneust I don't understand how you solved the situation. I have exactly the same errors, and my development console is full of errors. ?? @bmatthieu3 can you help?

<img width="1518" alt="Screenshot 2024-02-15 at 22 45 20" src="https://github.com/cds-astro/aladin-lite/assets/226224/06e67b10-35f6-4671-9bd9-00a173633b40">

**Comment by RobinMeneust** [comment] 2024-02-16 06:43
@onekiloparsec I still got the error. It's just that  it was much less frequent and it didn't prevent my app from working.

Note: I haven't used Aladin Lite since August.

**Comment by onekiloparsec** [comment] 2024-02-16 07:25
Interesting discussions here https://github.com/rustwasm/wasm-bindgen/issues/1578 and here https://stackoverflow.com/questions/75712197/rust-wasm-bindgen-recursive-use-of-an-object-detected-which-would-lead-to-unsaf

**Comment by onekiloparsec** [comment] 2024-03-03 10:18
Quick note saying this is a very annoying situation. @bmatthieu3 your commit to "make the bundle compatible with older browsers" is probably a bad idea, IMHO. It is quite a big challenge to support old browsers with such a sophisticated lib. Moreover, you make the JS part compatible, but how about the WASM part (form which originates the problem).

I would personnaly not target old browsers (anyway, none of the people in this thread support really old ones, as far as I can tell), hence the problem is elsewhere.

I will try to downgrade to `3.1.1`.

**Comment by bmatthieu3** [comment] 2024-03-27 16:50
Hi @RobinMeneust and @onekiloparsec,

Do you still have those errors with the recently deployed 3.3.x versions ? There is a page containing all the release of aladin lite deployed here: https://aladin.cds.unistra.fr/AladinLite/doc/release/
Thanks for your feedbacks,

**Comment by bmatthieu3** [comment] 2024-06-11 10:00
I think this issue has been solved in the develop branch and even in the last published beta version https://aladin.cds.unistra.fr/AladinLite/doc/release/ so I will close that issue. If anything goes wrong do not hesitate to reopen it.

**Closed by bmatthieu3** 2024-06-11 10:00 UTC
